spring:
#  profiles:
#    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

  datasource:
    platform: h2
    url: jdbc:h2:mem:test #配置h2数据库的连接地址
    driver-class-name: org.h2.Driver #配置JDBC Driver
    username: sa #配置数据库用户名
    password: #123456，配置数据库密码
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
#  redis:
#      database: 0
#      host: localhost
#      port: 6379
#      password:      # 密码（默认为空）
#      timeout: 6000ms  # 连接超时时长（毫秒）
#      jedis:
#        pool:
#          max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
#          max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#          max-idle: 10      # 连接池中的最大空闲连接
#          min-idle: 5       # 连接池中的最小空闲连接

  freemarker:
    suffix: .html
    request-context-attribute: request

# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8080
  servlet:
    context-path: /renren-admin

renren:
  redis:
    open: false  # 是否开启redis缓存  true开启   false关闭
  shiro:
    redis: false # true表示shiro session存到redis里，需要开启redis，才会生效【分布式场景】

logging:
  level: debug
  level.io.renren: debug
  path: logs/
  file: admin.log