spring:
  datasource.data: classpath:/sql/init-data.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    show-sql: true
    properties.hibernate.format_sql: false
    hibernate:
      ddl-auto: create-drop